<?php
/**
 * Not Exists Operator.
 *
 * @package     Database
 * @subpackage  Operators
 * @copyright   2021-2022 - JJJ and all BerlinDB contributors
 * @license     https://opensource.org/licenses/MIT MIT
 * @since       3.0.0
 */
namespace BerlinDB\Database\Operators;

defined( 'ABSPATH' ) || exit;

/**
 * NOT EXISTS operator — validates that a meta key does not exist.
 *
 * The NOT EXISTS check is implemented entirely by the Meta parser using a
 * LEFT JOIN + IS NULL pattern. This class returns an empty string from
 * get_sql() as a signal that there is no value fragment. Parsers guard
 * against the empty return with `! empty( $where )`.
 *
 * @since 3.0.0
 */
class NotExists extends Base {

	/**
	 * @since 3.0.0
	 * @var string
	 */
	protected $name = 'Not Exists';

	/**
	 * @since 3.0.0
	 * @var string
	 */
	protected $compare = 'NOT EXISTS';

	/**
	 * @since 3.0.0
	 * @var bool
	 */
	protected $positive = false;

	/**
	 * @since 3.0.0
	 * @var bool
	 */
	protected $multi = false;

	/**
	 * @since 3.0.0
	 * @var bool
	 */
	protected $numeric = false;

	/**
	 * Returns an empty string — NOT EXISTS has no value fragment.
	 *
	 * The actual NOT EXISTS SQL is generated by the Meta parser via a LEFT JOIN
	 * combined with `{alias}.{column} IS NULL`. Callers guard against the empty
	 * return with `! empty( $where )`.
	 *
	 * @since 3.0.0
	 *
	 * @param mixed  $value   Unused. Value is irrelevant for NOT EXISTS checks.
	 * @param string $pattern Unused.
	 *
	 * @return string Always empty string.
	 */
	public function get_sql( $value = null, $pattern = '%s' ) {

		// Nothing to prepare; NOT EXISTS has no value operand.
		return '';
	}
}
